### ISSUE TITLE
sir yo series wala program ma output 1.0000000 matra aauxa

### ISSUE THREAD

**Issue by prasannasapkota1717** [1sps/CLab#1] opened 2020-03-11 02:42 UTC
```
include<stdio.h>
void main()
{
	int i,j,n,fact;
	float sum=0,term;
	clrscr();
	printf("enter a number");
	scanf("%d",n);
	for(i=1;i<=n;i++)
	{
		for(j=1;j<=i;j++)
			fact=fact*j;
		term = 1/(float)(fact);
		sum+=term;

	}
	sum=sum+1;
	printf("the sum of the series is %f",sum);
	getch();
}
```

**Comment by 1sps** [comment] 2020-03-11 03:16
Please tell which exercise number.

**Comment by 1sps** [comment] 2020-03-11 03:17
`scanf("%d",n); 
`
is wrong here. It should have & operator. 

```
for(i=1;i<=n;i++)
{
    // need to add this
    // fact = 1; 
    for(j=1;j<=i;j++)
        fact=fact*j;

```
`fact` needs to be set to 1 as well. See comment in above code.

**Comment by prasannasapkota1717** [comment] 2020-03-11 16:56
> `scanf("%d",n); `
> is wrong here. It should have & operator.
> 
> ```
> for(i=1;i<=n;i++)
> {
>     // need to add this
>     // fact = 1; 
>     for(j=1;j<=i;j++)
>         fact=fact*j;
> ```
> 
> `fact` needs to be set to 1 as well. See comment in above code.



> `scanf("%d",n); `
> is wrong here. It should have & operator.
> 
> ```
> for(i=1;i<=n;i++)
> {
>     // need to add this
>     // fact = 1; 
>     for(j=1;j<=i;j++)
>         fact=fact*j;
> ```
> 
> `fact` needs to be set to 1 as well. See comment in above code.

thank u sir

**Comment by prasannasapkota1717** [comment] 2020-03-11 16:56
> > `scanf("%d",n); `
> > is wrong here. It should have & operator.
> > ```
> > for(i=1;i<=n;i++)
> > {
> >     // need to add this
> >     // fact = 1; 
> >     for(j=1;j<=i;j++)
> >         fact=fact*j;
> > ```
> > 
> > 
> > `fact` needs to be set to 1 as well. See comment in above code.
> 
> > `scanf("%d",n); `
> > is wrong here. It should have & operator.
> > ```
> > for(i=1;i<=n;i++)
> > {
> >     // need to add this
> >     // fact = 1; 
> >     for(j=1;j<=i;j++)
> >         fact=fact*j;
> > ```
> > 
> > 
> > `fact` needs to be set to 1 as well. See comment in above code.
> 
> thank u sir

was a silly mistake tho

**Comment by 1sps** [comment] 2020-03-12 02:44
Please close this issue if the problem is resolved now.

**Closed as completed** 2021-08-07 03:21 UTC
